### POST
POST localhost:8081/account/login HTTP/1.1
Content-Type: application/json

{
    "login": "popa"
    "password": "123123123"
}

### POST
POST localhost:8081/api/marina/createString HTTP/1.1
Content-Type: application/json

{
  "id": "1",
  "context": "popa"
}


